# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-29 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_name',
            field=models.CharField(max_length=200),
        ),
    ]
